### ISSUE TITLE
Error Importing on The Forge

### ISSUE THREAD

**Issue by avagdumortesin** [fryguy1013/pdftofoundry#10]
Trying to refresh my Bounties and Quests world with the new journal design and functions/clean up, I deleted all of the content from the Asset Library on The Forge, then cleared the settings in PDF to Foundry. When I attempt to import Bounty 6, it hangs at `Extracting npc 0`. Looking in the console, I'm seeing the following:
```
Uncaught (in promise) DOMException: Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at _0x3cccef (https://assets.forge-vtt.com/bazaar/modules/pdftofoundry/4.1.2/importer.mjs:1:24350)
    at new Promise (<anonymous>)
    at _ModuleImporter.emitImage (https://assets.forge-vtt.com/bazaar/modules/pdftofoundry/4.1.2/importer.mjs:1:24300)
    at _ModuleNpc.generate (https://assets.forge-vtt.com/bazaar/modules/pdftofoundry/4.1.2/FoundryGui.mjs:1:91090)
    at async _ModuleImporter.import (https://assets.forge-vtt.com/bazaar/modules/pdftofoundry/4.1.2/importer.mjs:1:32212)
    at async Module.generateData (https://assets.forge-vtt.com/bazaar/modules/pdftofoundry/4.1.2/importer.mjs:1:37327)
```
Module loadout:
![image](https://github.com/fryguy1013/pdftofoundry/assets/55938242/5c582b19-9cf6-4542-80e4-a4d7e6556847)
![image](https://github.com/fryguy1013/pdftofoundry/assets/55938242/5059154e-ede8-4179-a59d-c501d73c735f)

Testing with only the Token pack, Dorako UI/UX, and libwrapper shows the same error in the console, as does testing with Bounties 7 and 18.

**Comment by avagdumortesin** [comment]
It appears to be happening when I change the token frame from the default to `modules/pf2e-tokens-bestiaries/rings/ring512.webp`. Testing on my local system, it works as expected. Closing this and working with Forge support.
