### ISSUE TITLE
Import button missing, errors in console

### ISSUE THREAD

**Issue by Casao** [fryguy1013/pdftofoundry#29]
When attempting to setup this module, after activating the module and reloading, the button does not appear on my settings list. Checking the console, I see the following error messages:

```
vendor.mjs:1 Uncaught TypeError: Cannot redefine property: difference
    at Object.defineProperty [as f] (<anonymous>)
    at module.exports (vendor.mjs:1:28234)
    at module.exports (vendor.mjs:1:34785)
    at 7642 (vendor.mjs:2:17381)
    at __webpack_require__ (vendor.mjs:2:40552)
    at 3375 (vendor.mjs:2:34426)
    at __webpack_require__ (vendor.mjs:2:40552)
    at vendor.mjs:2:59595
```

```
foundry.js:655 Error: Failed to parse compendium art mapping for package 'PDF to Foundry Importer'. 
    at Hooks.onError (foundry.js:654:24)
    at CompendiumArt._registerArt (foundry-esm.js:60792:17)
```

This is on a server hosted on The Forge Foundry v12.331 with no other extensions enabled except the mandatory Forge extension -- I don't think I see anything from The Forge's extension in that stack trace, but I'm not familiar enough to be sure. Not sure if this is a forge issue or something that came about in .331 maybe?

**Comment by fryguy1013** [comment]
This is probably due to the way forge moves files to their s3 instance or whatever they due. I don't have access to Forge so I can't validate this
