### ISSUE TITLE
Failure Importing Strength of Thousands 2 on build 311

### ISSUE THREAD

**Issue by Josaphat** [fryguy1013/pdftofoundry#8]
Please let me know if there's a better forum for this.

It looks like the importer is running into some kind of issue on the second PDF of Strength of Thousands (afaict the first and third pdfs work without issue).

I'm running Foundry Version 11 build 311 from the Stable channel. pdftofoundry 4.1.1. nodejs is v18.18.0.

This error comes up in the logs:
```
FoundryVTT | 2023-10-01 06:34:02 | [info] electrified-water-ward.token.webp saved to pdftofoundry/strength-of-thousands-2
FoundryVTT | 2023-10-01 06:34:02 | [info] electrified-water-ward.actor.webp saved to pdftofoundry/strength-of-thousands-2
FoundryVTT | 2023-10-01 06:34:02 | [info] FoundryVTT | Created Actor with id [aKshBYP0rbzClBb6]
FoundryVTT | 2023-10-01 06:34:02 | [info] FoundryVTT | Created Folder with id [GO7itmcQEPVbdZSx]
FoundryVTT | 2023-10-01 06:34:02 | [info] FoundryVTT | Created JournalEntry with id [7ANDdsjORQBEo4Mm]
FoundryVTT | 2023-10-01 06:34:03 | [error] Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
    at Tokenizer.stateBeforeEntity (/home/jos/foundryvtt/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:584:47)
    at Tokenizer.parse (/home/jos/foundryvtt/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:848:26)
    at Tokenizer.write (/home/jos/foundryvtt/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:159:14)
    at Parser.write (/home/jos/foundryvtt/resources/app/node_modules/htmlparser2/lib/Parser.js:459:28)
    at sanitizeHtml (/home/jos/foundryvtt/resources/app/node_modules/sanitize-html/index.js:588:10)
    at cleanHTML (file:///home/jos/foundryvtt/resources/app/dist/database/validators.mjs:1:233)
    at HTMLField.sanitizeHTMLField [as sanitize] (file:///home/jos/foundryvtt/resources/app/dist/database/sanitization.mjs:1:1235)
    at Function._sanitizeFields (file:///home/jos/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:7729)
    at Function._sanitizeFields (file:///home/jos/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:7956)
    at file:///home/jos/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:7863
```

This seems to coincide with the progress bar reaching "Extracting npc 65". The error (`Cannot read properties of undefined (reading '0')`) is displayed in a red pop-up, but then lots more blue pop-ups go by. The progress bar doesn't change, though.

Let me know if there's anything I can do to help resolve.

**Comment by bryontrip** [comment]
I am having the same issue importing Extinction Curse: Legacy of the Lost God (book 2).

pdftofoundry 4.1.1
All other modules disabled.

ubuntu@xxxxx:~$ node -v
v18.14.2

From the JS console:
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at Tokenizer.stateBeforeEntity (home/foundry/foundry/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:584:47)
    at Tokenizer.parse (home/foundry/foundry/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:848:26)
    at Tokenizer.write (home/foundry/foundry/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:159:14)
    at Parser.write (home/foundry/foundry/resources/app/node_modules/htmlparser2/lib/Parser.js:459:28)
    at sanitizeHtml (home/foundry/foundry/resources/app/node_modules/sanitize-html/index.js:588:10)
    at cleanHTML (/home/foundry/foundry/resources/app/dist/database/validators.mjs:1:233)
    at HTMLField.sanitizeHTMLField [as sanitize] (/home/foundry/foundry/resources/app/dist/database/sanitization.mjs:1:1235)
    at JournalEntry._sanitizeFields (/home/foundry/foundry/resources/app/dist/database/backend/server-document.mjs:1:7729)
    at JournalEntry._sanitizeFields (/home/foundry/foundry/resources/app/dist/database/backend/server-document.mjs:1:7956)
    at /home/foundry/foundry/resources/app/dist/database/backend/server-document.mjs:1:7863

**Comment by bryontrip** [comment]
> Please let me know if there's a better forum for this.
> 
> It looks like the importer is running into some kind of issue on the second PDF of Strength of Thousands (afaict the first and third pdfs work without issue).
> 
> I'm running Foundry Version 11 build 311 from the Stable channel. pdftofoundry 4.1.1. nodejs is v18.18.0.
> 
> This error comes up in the logs:
> 
> ```
> FoundryVTT | 2023-10-01 06:34:02 | [info] electrified-water-ward.token.webp saved to pdftofoundry/strength-of-thousands-2
> FoundryVTT | 2023-10-01 06:34:02 | [info] electrified-water-ward.actor.webp saved to pdftofoundry/strength-of-thousands-2
> FoundryVTT | 2023-10-01 06:34:02 | [info] FoundryVTT | Created Actor with id [aKshBYP0rbzClBb6]
> FoundryVTT | 2023-10-01 06:34:02 | [info] FoundryVTT | Created Folder with id [GO7itmcQEPVbdZSx]
> FoundryVTT | 2023-10-01 06:34:02 | [info] FoundryVTT | Created JournalEntry with id [7ANDdsjORQBEo4Mm]
> FoundryVTT | 2023-10-01 06:34:03 | [error] Cannot read properties of undefined (reading '0')
> TypeError: Cannot read properties of undefined (reading '0')
>     at Tokenizer.stateBeforeEntity (/home/jos/foundryvtt/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:584:47)
>     at Tokenizer.parse (/home/jos/foundryvtt/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:848:26)
>     at Tokenizer.write (/home/jos/foundryvtt/resources/app/node_modules/htmlparser2/lib/Tokenizer.js:159:14)
>     at Parser.write (/home/jos/foundryvtt/resources/app/node_modules/htmlparser2/lib/Parser.js:459:28)
>     at sanitizeHtml (/home/jos/foundryvtt/resources/app/node_modules/sanitize-html/index.js:588:10)
>     at cleanHTML (file:///home/jos/foundryvtt/resources/app/dist/database/validators.mjs:1:233)
>     at HTMLField.sanitizeHTMLField [as sanitize] (file:///home/jos/foundryvtt/resources/app/dist/database/sanitization.mjs:1:1235)
>     at Function._sanitizeFields (file:///home/jos/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:7729)
>     at Function._sanitizeFields (file:///home/jos/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:7956)
>     at file:///home/jos/foundryvtt/resources/app/dist/database/backend/server-document.mjs:1:7863
> ```
> 
> This seems to coincide with the progress bar reaching "Extracting npc 65". The error (`Cannot read properties of undefined (reading '0')`) is displayed in a red pop-up, but then lots more blue pop-ups go by. The progress bar doesn't change, though.
> 
> Let me know if there's anything I can do to help resolve.

Found some other stuff in Foundry was giving me this error as well, like simply casting any spell.

I updated from 9 to 11 using the UI. This seems to have caused issues for some. The solution for me was to reinstall using the latest version.

Here is the guide for a Linux re-install. I think the other OSes are in there too.

https://foundryvtt.wiki/en/setup/linux-installation#optional-g-performing-a-clean-reinstallupdate

Hope this helps!

**Comment by fryguy1013** [comment]
Looks like this is a v11 issue? Happens with other modules unrelated to pdf to foundry

https://discord.com/channels/170995199584108546/722566083499786352/1171518792610893945
